name: melissamahler
favicon: null
layout_spectrum: 1
typography_spectrum: 0.50124
title: 'Melissa Mahler '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#e90018'
    - '#191919'
    - '#bdbdbd'
    - '#f67280'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.29649590188637376
purpose: []
